### ISSUE TITLE
recovery mode?

### ISSUE THREAD

**Issue by toxicfox2491** [Myp3a/GenshinConfigurator#1]
I dont know if this is really an issue but when ever I try to launch the configurator it tells me my config is broken? then I can edit the file but theres text at the bottom saying its fine? I dont exactly know how to use/pass this window
I also looked through the GUI usage wiki and I couldnt find how to get passed the recovery mode window which just gives me a raw editor that idk how to use

so any ideas on how I could get passed it? or maybe Im being dumb in which case Im sorry for wasting ur time lmao

**Comment by toxicfox2491** [comment]
> Hello, and thank you for the issue!
> 
> If recovery mode says that config is fine, it's syntactically correct. So the issue is somewhere where the config is parsed and being worked with. Can you please provide the config, so I can test where it fails? There are no sensitive data inside it, only ingame settings.
no problem! I was just a bit confused since this was my first time trying to use the program


{"deviceUUID":"","userLocalDataVersionId":"0.0.1","deviceLanguageType":1,"deviceVoiceLanguageType":1,"selectedServerName":"os_euro","localLevelIndex":0,"deviceID":"","targetUID":"","curAccountName":"","uiSaveData":"{\"currWindowResolutionIndex\":6}","inputData":"{\"scriptVersion\":\"OSRELWin2.7.0\",\"mouseSensitivity\":10.0,\"joypadSenseIndex\":2,\"joypadFocusSenseIndex\":2,\"joypadInvertCameraX\":false,\"joypadInvertCameraY\":false,\"joypadInvertFocusCameraX\":false,\"joypadInvertFocusCameraY\":false,\"mouseSenseIndex\":3,\"mouseFocusSenseIndex\":3,\"touchpadSenseIndex\":2,\"touchpadFocusSenseIndex\":5,\"enableTouchpadFocusAcceleration\":false,\"lastJoypadDefaultScale\":1.0,\"lastJoypadFocusScale\":1.0,\"lastPCDefaultScale\":0.75,\"lastPCFocusScale\":1.0,\"lastTouchDefaultScale\":1.0,\"lastTouchFcousScale\":1.0,\"switchWalkRunByBtn\":false,\"skiffCameraAutoFix\":true,\"skiffCameraAutoFixInCombat\":false,\"cameraDistanceRatio\":0.3688570559024811,\"wwiseVibration\":true}","graphicsData":"{\"currentVolatielGrade\":-1,\"customVolatileGrades\":[{\"key\":1,\"value\":2},{\"key\":2,\"value\":1},{\"key\":3,\"value\":1},{\"key\":4,\"value\":1},{\"key\":5,\"value\":1},{\"key\":6,\"value\":1},{\"key\":7,\"value\":1},{\"key\":8,\"value\":1},{\"key\":9,\"value\":1},{\"key\":10,\"value\":1},{\"key\":11,\"value\":1},{\"key\":12,\"value\":1},{\"key\":13,\"value\":1},{\"key\":16,\"value\":1},{\"key\":15,\"value\":1},{\"key\":17,\"value\":1}],\"volatileVersion\":\"OSRELWin2.7.0\"}","globalPerfData":"{\"saveItems\":[{\"entryType\":18,\"index\":2,\"itemVersion\":\"OSRELWin2.7.0\"}],\"truePortedFromGraphicData\":true,\"portedVersion\":\"OSRELWin2.7.0\",\"portedFromGraphicData\":false}","miniMapConfig":0,"enableCameraSlope":true,"enableCameraCombatLock":true,"completionPkg":false,"completionPlayGoPkg":false,"onlyPlayWithPSPlayer":false,"needPlayGoFullPkgPatch":false,"resinNotification":true,"exploreNotification":true,"volumeGlobal":5,"volumeSFX":10,"volumeMusic":10,"volumeVoice":10,"audioAPI":-1,"audioDynamicRange":0,"audioOutput":0,"_audioSuccessInit":true,"enableAudioChangeAndroidMinimumBufferCapacity":true,"audioAndroidMiniumBufferCapacity":2048,"motionBlur":false,"gyroAiming":false,"firstHDRSetting":false,"maxLuminosity":0.0,"uiPaperWhite":0.0,"scenePaperWhite":0.0,"gammaValue":2.4624998569488525,"_overrideControllerMapKeyList":[],"_overrideControllerMapValueList":[],"rewiredDisableKeyboard":false,"disableRewiredDelayInit":false,"lastSeenPreDownloadTime":0,"mtrCached":true,"mtrIsOpen":true,"mtrMaxTTL":32,"mtrTimeOut":5000,"mtrTraceCount":5,"mtrAbortTimeOutCount":3,"mtrAutoTraceInterval":3600,"mtrTraceCDEachReason":600,"_customDataKeyList":[],"_customDataValueList":[]}

**Comment by Myp3a** [comment]
The problem was in the code that manages controls settings - it wasn't expecting empty override list. That's because the game adds an input device to the config only when it has changes in settings.

I've uploaded a new release that should work fine now.

**Comment by toxicfox2491** [comment]
> 

tysm I didnt expect the controls to be the issue lol
