### ISSUE TITLE
Program Crash when change Joystick L2 and R2 Fuction Mapping

### ISSUE THREAD

**Issue by HandisableL** [Myp3a/GenshinConfigurator#2]
device:Dualshock4
GUID:cd9718bf-a87a-44bc-8716-60a0def28a9f
It's list 3 devices: Unknown device(2001000),Unknown device(2000000),and keyboard
when i plug the dualshock4 in via USB-cable,and select 2001000,A warning widows pop-up
debug info:
System.ArgumentOutOfRangeException: InvalidArgument=“39”的值对于“SelectedIndex”无效。
参数名: SelectedIndex
   在 System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   在 GenshinConfigurator.MainWin.<Populate_Controls>g__Add_Controller_Binding|21_5(Keybind bind, String[] bindings, Int32 mlt, <>c__DisplayClass21_0& )
   在 GenshinConfigurator.MainWin.Populate_Controls()
   在 GenshinConfigurator.MainWin.Reload_Controls(Object sender, EventArgs e)
   在 System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   在 System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   在 System.Windows.Forms.ComboBox.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

when select 2000000:
System.ArgumentOutOfRangeException: InvalidArgument=“29”的值对于“SelectedIndex”无效。
参数名: SelectedIndex
   在 System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   在 GenshinConfigurator.MainWin.<Populate_Controls>g__Add_Controller_Binding|21_5(Keybind bind, String[] bindings, Int32 mlt, <>c__DisplayClass21_0& )
   在 GenshinConfigurator.MainWin.Populate_Controls()
   在 GenshinConfigurator.MainWin.Reload_Controls(Object sender, EventArgs e)
   在 System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   在 System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   在 System.Windows.Forms.ComboBox.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

but first time i open it,it show everything correctly,but after edit L2 and R2 feature,mapping seems totally wrong in game.
and when i re-open the configurator try to remapping it,warning things happend.

Maybe it reading wrong parameter when i change the default key config in game?
I read the WIKI and try to switch the ActionID,things work perfectly.

sorry for my bad english.
![error_message](https://user-images.githubusercontent.com/81951753/189613719-7871321c-bb0a-4495-81a4-73506d5277e6.png)

**Comment by Myp3a** [comment]
This is probably because DualShock 4 and DualSense have the same name. I don't have an DS4, so couldn't check if it has different attributes than DualSense.

Thank you for the ID! I'll find a DS4 in a few days, and will add support for it.

**Comment by Myp3a** [comment]
Should be fixed in [3.1 release](https://github.com/Myp3a/GenshinConfigurator/releases/tag/v3.1.0.0). However, I tested it on virtual DS4 - can you verify it on real controller?

**Comment by HandisableL** [comment]
> Should be fixed in [3.1 release](https://github.com/Myp3a/GenshinConfigurator/releases/tag/v3.1.0.0). However, I tested it on virtual DS4 - can you verify it on real controller?

I try DS4 in 3.1.0.0,and it show nothing in Controls/Input Device list,
![图片](https://user-images.githubusercontent.com/81951753/195047434-a0e1e6c9-8288-41dd-ace6-59f247280308.png)

but i can use DS4 normally via USB CABLE in game
[RAW config (mapping part).txt](https://github.com/Myp3a/GenshinConfigurator/files/9753511/RAW.config.mapping.part.txt)

Do I need reset all game settings to make it work correctly?

**Comment by Myp3a** [comment]
Please, change any controller mapping in game - that will generate the config for it. Unfortunately, that's a game limitation.

**Comment by HandisableL** [comment]
> Please, change any controller mapping in game - that will generate the config for it. Unfortunately, that's a game limitation.

I manually delete all remapping part from raw config and now it can show in device list correctly,thanks
but when i use CONFIGURATOR change sprint from R2(Which i set in game) to L2,and set Aiming Mode from L2 to R2.
They both become malfunctional in game,maybe Game limitation too?
