### ISSUE TITLE
Will not allow tab for rebinding 

### ISSUE THREAD

**Issue by orariley70** [Myp3a/GenshinConfigurator#3]
Tab can't be rebound because it is not properly captured, instead selecting the next UI element.

**Comment by Myp3a** [comment]
Thanks for the issue! Should be fixed in [v.3.5](https://github.com/Myp3a/GenshinConfigurator/releases/tag/v3.5.0.0). Can you check, if it works for you, please?

**Comment by orariley70** [comment]
I did try with a fresh config, and it works, however, I did not take a screenshot.

**Comment by orariley70** [comment]
![image](https://user-images.githubusercontent.com/96967473/225639265-a28440f0-1b7f-43f4-a026-a22f4872f14a.png)
