### ISSUE TITLE
need command line feature to load saved config.

### ISSUE THREAD

**Issue by HandisableL** [Myp3a/GenshinConfigurator#4]
Hello.I run Genshin on two stream device,and it has different controll device(touchscreen ->controller for tablet,kb+mouse for another computer)
Is it possible to add a cmdline to toggle to change default controller in game?(I need change from KB+Mouse to Console everytime,this game can't support auto switch input device,which is awful.)
thanks

**Comment by Myp3a** [comment]
Unfortunately, this isn't possible. There's no device selection in the config, game decides, what controller it will be using. This one would require injecting code into Genshin's process, what's against the ToS
